# Generated by Django 4.1.7 on 2023-02-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='created_by',
            new_name='author',
        ),
    ]
