# Generated by Django 4.1.7 on 2023-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
